BOARDCPPSRC = $(BOARD_DIR)/board_configuration.cpp

DDEFS += -DSTM32F407xx

ifeq ($(VAR_DEF_ENGINE_TYPE),)
  VAR_DEF_ENGINE_TYPE = -DDEFAULT_ENGINE_TYPE=engine_type_e::DEFAULT_FRANKENSO
endif

DDEFS += -DHW_FRANKENSO=1
DDEFS += $(DEFAULT_ENGINE_TYPE)

BUNDLE_OPENOCD = yes

DDEFS += -DSTM32_ADC_USE_ADC3=TRUE
