      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi
          sudo apt-get install -y binutils-arm-none-eabi
          sudo apt-get install -y libnewlib-arm-none-eabi
          sudo apt-get install -y make
          sudo apt-get install -y mtools

          echo "===== CHECK MCOPY ====="
          command -v mcopy
          mcopy -V
          echo "===== MCOPY OK ====="

      - name: Check custom board files
        working-directory: firmware
        run: |
          echo "===== CURRENT DIRECTORY ====="
          pwd

          echo "===== BOARDS DIRECTORY ====="
          ls -la config/boards/

          echo "===== DEVBOX DIRECTORY ====="
          ls -la config/boards/devebox-f407/

          echo "===== META INFO ====="
          cat config/boards/devebox-f407/meta-info.env

      - name: Compile devebox-f407
        working-directory: firmware
        run: |
          chmod +x bin/compile.sh
          ./bin/compile.sh config/boards/devebox-f407/meta-info.env
